CREATE TABLE Bookmarks (
    BookmarkID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL,
    ArticleID INTEGER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ArticleID) REFERENCES Articles(ArticleID) ON DELETE CASCADE
);